# Generated by Django 3.2.2 on 2022-03-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forget_password_token',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
